In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

from nRC_parametrization import SOC_func
from nRC_parametrization import SOC_to_OCV
from nRC_parametrization import simulate_battery_model
from nRC_parametrization import RMSE

In [2]:
current_dir = Path.cwd()

parameters_path = current_dir.parent / "validation" / "parameters_for_validation.csv"

static_parameters_dir = current_dir.parent.parent / "Parameters" / "static_parameters"

profiles_dir = current_dir.parent.parent / "Data_preprocessing" / "profiles"

df_parameters = pd.read_csv(parameters_path)

In [3]:
df_parameters

,profile,Battery_ID,SOH,T,SOC,Q_Ah,eta,OCV_file_name,R0,R,tau
0,NEDC,1,94,25,55-35,3.289069,0.993163,OCV_1_+25.csv,0.040102,[ 0.18500965 -0.15799339],[74.79622419 74.46096847]
1,NEDC,1,94,25,75-55,3.289069,0.993163,OCV_1_+25.csv,0.043565,[ 2.38419122 -2.33588565],[76.6982802 75.91917751]
2,NEDC,1,94,25,95-75,3.289069,0.993163,OCV_1_+25.csv,0.044178,[-3.1062521 3.13802852],[76.12695194 76.00372429]
3,UDDS,1,94,25,55-35,3.289069,0.993163,OCV_1_+25.csv,0.038852,[ 0.05812656 -0.0271138 ],[70.43697862 64.5548939 ]
4,UDDS,1,94,25,75-55,3.289069,0.993163,OCV_1_+25.csv,0.040251,[ 0.14614713 -0.09671487],[70.3419654 63.7584806]
...,...,...,...,...,...,...,...,...,...,...,...
265,impulse_288_s,5,98,35,75-55,3.434987,0.991690,OCV_5_+35.csv,0.041669,[ 0.11122546 -0.09116178],[63.50124231 51.079858 ]
266,impulse_288_s,5,98,35,95-75,3.434987,0.991690,OCV_5_+35.csv,0.037150,[ 0.04318691 -0.02255343],[60.161704 49.73728641]
267,impulse_72_s,5,98,35,55-35,3.434987,0.991690,OCV_5_+35.csv,0.037404,[ 0.0295919 -0.01634364],[23.43636714 5.62030503]
268,impulse_72_s,5,98,35,75-55,3.434987,0.991690,OCV_5_+35.csv,0.038704,[ 0.0609155 -0.0486512],[15.63131377 6.06766978]
269,impulse_72_s,5,98,35,95-75,3.434987,0.991690,OCV_5_+35.csv,0.037207,[ 0.04074654 -0.02637262],[18.3403936 5.40681083]

In [4]:
df_profiles_description =  pd.read_csv(static_parameters_dir / "profiles_description_static_parameters.csv")

In [5]:
df_profiles_description

,bat_num,temp,profile,U_start_V,U_end_V,file_name,Q_Ah,eta,OCV_file_name,SOC_start,SOC_end,SOH
0,1,25,impulse_72_s,4.11093,4.10372,1_+25_impulse_72_s_01.csv,3.289069,0.993163,OCV_1_+25.csv,96.579538,95.849146,93.973411
1,1,25,impulse_144_s,4.10372,4.09365,1_+25_impulse_144_s_02.csv,3.289069,0.993163,OCV_1_+25.csv,95.849146,94.516093,93.973411
2,1,25,impulse_288_s,4.09365,4.07940,1_+25_impulse_288_s_03.csv,3.289069,0.993163,OCV_1_+25.csv,94.516093,91.610379,93.973411
3,1,25,impulse_72_s,4.07940,4.07487,1_+25_impulse_72_s_04.csv,3.289069,0.993163,OCV_1_+25.csv,91.610379,90.357663,93.973411
4,1,25,impulse_144_s,4.07487,4.06139,1_+25_impulse_144_s_05.csv,3.289069,0.993163,OCV_1_+25.csv,90.357663,86.572312,93.973411
...,...,...,...,...,...,...,...,...,...,...,...,...
535,5,35,NEDC,3.95779,3.75069,5_+35_NEDC_02.csv,3.434987,0.991690,OCV_5_+35.csv,76.178929,55.833428,98.142481
536,5,35,NEDC,3.75069,3.59529,5_+35_NEDC_03.csv,3.434987,0.991690,OCV_5_+35.csv,55.833428,36.393882,98.142481
537,5,35,WLTC,4.11297,3.90308,5_+35_WLTC_01.csv,3.434987,0.991690,OCV_5_+35.csv,96.318219,70.142435,98.142481
538,5,35,WLTC,3.90308,3.68861,5_+35_WLTC_02.csv,3.434987,0.991690,OCV_5_+35.csv,70.142435,49.435377,98.142481
539,5,35,WLTC,3.68861,3.53812,5_+35_WLTC_03.csv,3.434987,0.991690,OCV_5_+35.csv,49.435377,29.703011,98.142481

In [6]:
profiles_for_validation = ["UDDS", "NEDC", "WLTC"]

SOC_ranges = {
    "95-75": "01",
    "75-55": "02",
    "55-35": "03"
}

df_validation = df_parameters.copy()

for p in ["UDDS", "NEDC", "WLTC"]:
    df_validation[f"{p}_rmse"] = np.nan


for idx, row in df_parameters.iterrows():
    battery_id = row["Battery_ID"]
    temp = row["T"]
    soc_range = row["SOC"]
    Q_Ah = row["Q_Ah"]
    eta = row["eta"]

    df_OCV = pd.read_csv(static_parameters_dir / row["OCV_file_name"])

    for profile_name in profiles_for_validation:
        profile_file_name = f'{battery_id}_+{temp}_{profile_name}_{SOC_ranges[soc_range]}.csv'
        
        df_profile = pd.read_csv(profiles_dir / profile_file_name)

        
        
        z0 = df_profiles_description.loc[df_profiles_description["file_name"] == profile_file_name, "SOC_start"].iloc[0]
        
        t = df_profile["t,s"].values
        I = df_profile["I,A"].values
        U = df_profile["U,V"].values
        
        SOC = SOC_func(I, t, z0, Q_Ah, eta)
        
        OCV = SOC_to_OCV(SOC, df_OCV)

        R0 = float(row["R0"])
        R = np.fromstring(row["R"].strip("[]"), sep=" ")
        tau = np.fromstring(row["tau"].strip("[]"), sep=" ")
        
        dynamic_parameters = {'R0': R0, 'R': R, 'tau': tau}
        
        U_sim = simulate_battery_model(I, t, OCV, eta, Q_Ah, dynamic_parameters)
        
        U_rmse = RMSE(U, U_sim)

        df_validation.loc[idx, f"{profile_name}_rmse"] = U_rmse

        print(idx)

0
0
0
1
1
1
2
2
2
3
3
3
4
4
4
5
5
5
6
6
6
7
7
7
8
8
8
9
9
9
10
10
10
11
11
11
12
12
12
13
13
13
14
14
14
15
15
15
16
16
16
17
17
17
18
18
18
19
19
19
20
20
20
21
21
21
22
22
22
23
23
23
24
24
24
25
25
25
26
26
26
27
27
27
28
28
28
29
29
29
30
30
30
31
31
31
32
32
32
33
33
33
34
34
34
35
35
35
36
36
36
37
37
37
38
38
38
39
39
39
40
40
40
41
41
41
42
42
42
43
43
43
44
44
44
45
45
45
46
46
46
47
47
47
48
48
48
49
49
49
50
50
50
51
51
51
52
52
52
53
53
53
54
54
54
55
55
55
56
56
56
57
57
57
58
58
58
59
59
59
60
60
60
61
61
61
62
62
62
63
63
63
64
64
64
65
65
65
66
66
66
67
67
67
68
68
68
69
69
69
70
70
70
71
71
71
72
72
72
73
73
73
74
74
74
75
75
75
76
76
76
77
77
77
78
78
78
79
79
79
80
80
80
81
81
81
82
82
82
83
83
83
84
84
84
85
85
85
86
86
86
87
87
87
88
88
88
89
89
89
90
90
90
91
91
91
92
92
92
93
93
93
94
94
94
95
95
95
96
96
96
97
97
97
98
98
98
99
99
99
100
100
100
101
101
101
102
102
102
103
103
103
104
104
104
105
105
105
106
106
106
107
107
107
108
108
108
109
109
109
110
110
110
111
111
111
112
112
112
113
113
113
114
114
114
115
115
115
116
116
116
117
117
117
118
118
118
119
119
119
120
120
120
121
121
121
122
122
122
123
123
123
124
124
124
125
125
125
126
126
126
127
127
127
128
128
128
129
129
129
130
130
130
131
131
131
132
132
132
133
133
133
134
134
134
135
135
135
136
136
136
137
137
137
138
138
138
139
139
139
140
140
140
141
141
141
142
142
142
143
143
143
144
144
144
145
145
145
146
146
146
147
147
147
148
148
148
149
149
149
150
150
150
151
151
151
152
152
152
153
153
153
154
154
154
155
155
155
156
156
156
157
157
157
158
158
158
159
159
159
160
160
160
161
161
161
162
162
162
163
163
163
164
164
164
165
165
165
166
166
166
167
167
167
168
168
168
169
169
169
170
170
170
171
171
171
172
172
172
173
173
173
174
174
174
175
175
175
176
176
176
177
177
177
178
178
178
179
179
179
180
180
180
181
181
181
182
182
182
183
183
183
184
184
184
185
185
185
186
186
186
187
187
187
188
188
188
189
189
189
190
190
190
191
191
191
192
192
192
193
193
193
194
194
194
195
195
195
196
196
196
197
197
197
198
198
198
199
199
199
200
200
200
201
201
201
202
202
202
203
203
203
204
204
204
205
205
205
206
206
206
207
207
207
208
208
208
209
209
209
210
210
210
211
211
211
212
212
212
213
213
213
214
214
214
215
215
215
216
216
216
217
217
217
218
218
218
219
219
219
220
220
220
221
221
221
222
222
222
223
223
223
224
224
224
225
225
225
226
226
226
227
227
227
228
228
228
229
229
229
230
230
230
231
231
231
232
232
232
233
233
233
234
234
234
235
235
235
236
236
236
237
237
237
238
238
238
239
239
239
240
240
240
241
241
241
242
242
242
243
243
243
244
244
244
245
245
245
246
246
246
247
247
247
248
248
248
249
249
249
250
250
250
251
251
251
252
252
252
253
253
253
254
254
254
255
255
255
256
256
256
257
257
257
258
258
258
259
259
259
260
260
260
261
261
261
262
262
262
263
263
263
264
264
264
265
265
265
266
266
266
267
267
267
268
268
268
269
269
269

In [7]:
df_validation[["UDDS_rmse", "NEDC_rmse", "WLTC_rmse"]].describe()

        UDDS_rmse   NEDC_rmse   WLTC_rmse
count  270.000000  270.000000  270.000000
mean     0.006253    0.007084    0.010511
std      0.004322    0.005031    0.006616
min      0.000858    0.000875    0.001549
25%      0.003505    0.003876    0.006339
50%      0.004803    0.005692    0.008714
75%      0.008700    0.009589    0.014119
max      0.026015    0.035705    0.044176

In [8]:
df_validation.to_csv(current_dir.parent / "validation" / "validation_results.csv", index=False)